Thinknetica RoR basic part5 implementation
k-gavrilov/ror_basic_test-guru pull request #4
Opened 2018-09-23 21:08 UTC by k-gavrilov

2018-09-24 14:36 UTC, iBublik requested changes

2018-09-24 14:36 UTC, iBublik commented on app/models/category.rb
> +  has_many :tests
При создании `has_*` ассоциации стоит указывать что делать с дочерними записями при удалении родителя (опция dependent). Сейчас ты не сможешь удалить категорию, у которой есть тесты

2018-09-24 14:36 UTC, iBublik commented on app/models/test.rb
> +  belongs_to :user, -> { where role: "Author" }, dependent: :destroy
Лучше придерживаться какого-то порядка - описывать сначала belongs_to связи, потом has_many.
Не очень говорящее название ассоциации. Сложно понять, что за пользователь вернется при вывзове `test.user`. Дай более очевидное имя (связи не обязаны совпадать по имени с моделью)
Ограничение `where(role: 'Author')` не сильно полезно. Если пользователь имел такую роль в системе, потом его уволили и он стал обычным User-ом, это не значит что он перестал быть автором этого теста.
Так же непонятно для чего указана опция `dependent: :destroy`. При удалении этого теста почему-то удалится и его автор :)

2018-09-24 14:36 UTC, iBublik commented on app/models/test.rb
> +    Category.find_by(title: category_title).tests.order(:title).pluck(:title)
Метод теперь возвращает названия категорий, а не тестов. 
Ассоциации позволят упростить запрос, но ты их немного неверно использовал. Посмотри примеры в документации, там как раз примеры joins с ассоциациями

2018-09-24 14:36 UTC, iBublik commented on app/models/user.rb
> +  has_many :works, class_name: "Test", foreign_key: :author_id
Лучше `own_tests` или `created_tests`

2018-09-24 14:36 UTC, iBublik commented on db/migrate/20180923140332_add_author_id_to_test.rb
> +    add_reference(:tests, :author, foreign_key: {to_table: :users})
Избавься от круглых скобок - DSL миграций выглядит выразительнее без них

2018-09-24 14:36 UTC, iBublik commented on db/migrate/20180923142344_add_role_to_user.rb
> +  def up
Зачем писать отдельно up/down метод?

2018-09-24 14:36 UTC, iBublik commented on db/migrate/20180923142344_add_role_to_user.rb
> +    change_column :users, :role, :string, null: false
Ты же строкой выше создал поле, можно добавить ограничение сразу при создании - `add_column :users, :role, :string, null: false`

2018-09-24 14:36 UTC, iBublik commented on db/seeds.rb
> +  {title: "HTML Basic", category_id: categories[0].id, author_id: users[0]},
Теперь можно писать `category: categories[0]`

2018-09-24 14:36 UTC, iBublik commented on db/migrate/20180923122318_create_tests_users_join_table.rb
> +    create_join_table :users, :tests do |t|
Не вижу преимуществ перед обычной таблицей. А вот недостаток есть - отстутствие id не позволит связать эту таблицу с другой сущностью. Например, если мы захотим хранить ответы, выбранные пользователем при прохождении теста - логичнее всего было бы хранить id попытки прохождения и id ответа. Но у таблицы с попытками прохождения id нет, так что придется как-то по-другому это делать

2018-09-24 14:36 UTC, iBublik commented on db/migrate/20180923122318_create_tests_users_join_table.rb
> +      t.index [:user_id, :test_id], unique: true
Вообще у нас не запрещено дважды проходить один и тот же тест.
И в целом я бы оставил 2 отдельных индекса. Иначе, если мы захотим получить всех пользователей, которые проходили какой-то конкретный тест, такой запрос не сможет использовать индекс, будет полный скан таблицы. А с раздельными индексами все будет ок.

2018-10-02 19:44 UTC, k-gavrilov commented on db/migrate/20180923142344_add_role_to_user.rb
> +  def up
Иначе SQLite ругается:
https://stackoverflow.com/a/6710280

2018-10-02 19:46 UTC, k-gavrilov commented on app/models/test.rb
> +    Category.find_by(title: category_title).tests.order(:title).pluck(:title)
Не стал менять. На самом деле, он возвращает название тестов. Мы работаем с тестами в конечном итоге:
```
ests.order(:title).pluck(:title)
```

2018-10-02 19:48 UTC, k-gavrilov commented on db/migrate/20180923142344_add_role_to_user.rb
> +    change_column :users, :role, :string, null: false
Иначе SQLite ругается:
https://stackoverflow.com/a/6710280

2018-10-03 06:53 UTC, iBublik requested changes

2018-10-03 06:53 UTC, iBublik commented on app/models/test.rb
> +    Category.find_by(title: category_title).tests.order(:title).pluck(:title)
Ты прав, это я не заметил. Но тут стало 2 запроса (поиски категории -> поиск тестов этой категории), что не очень оптимально. Нужно joins использовать

2018-10-03 06:53 UTC, iBublik commented on app/models/author.rb
> +class Author < User
Не нужно усложнять, автор - обычный пользователь, для этого не надо отдельную модель выделять

2018-10-03 06:53 UTC, iBublik commented on app/models/author.rb
> +  has_many :created_tests, class_name: "Test", foreign_key: :author_id
Что будет с тестами при удалении автора?

2018-10-03 06:53 UTC, iBublik commented on app/models/student.rb
> +class Student < User
Это тоже лишнее усложнение. Получается, если ты автор теста, то ты уже не сможешь проходить тесты

2018-10-03 06:53 UTC, iBublik commented on db/migrate/20181002182742_add_type_to_user.rb
> +    add_column :users, :type, :string
Достаточно метода `change`, рельсы знают как откатить его

2018-10-03 06:53 UTC, iBublik commented on db/migrate/20181002182742_add_type_to_user.rb
> +    change_column :users, :type, :string, null: false
При создании поля можно сразу указать опцию `null: false`

2018-10-03 06:53 UTC, iBublik commented on db/migrate/20181002182742_add_type_to_user.rb
> +    change_column :users, :type, :string, null: false
Истинная причина того, что ты не можешь сразу указать опцию указана в этом ответе - https://stackoverflow.com/a/3170700. Просто удали все записи, пересоздай базу с нуля

2018-10-04 07:14 UTC, iBublik approved these changes

2018-10-04 07:14 UTC, iBublik commented on app/models/user.rb
> +  has_many :created_tests, class_name: "Test", foreign_key: :author_id, dependent: :destroy
Правильнее было бы обнулять автора у тестов. Если пользователя удалили из системы, это не значит что весь его контент должен пропасть

2018-10-04 17:36 UTC, merged