Implementation for Thinknetica RoR basic part 6
k-gavrilov/ror_basic_test-guru pull request #5
Opened 2018-10-08 17:18 UTC by k-gavrilov

2018-10-09 10:44 UTC, iBublik requested changes

2018-10-09 10:44 UTC, iBublik commented on app/models/answer.rb
> +  validate :validate_number_of_answers
Валидация не позволит изменить ответ, если у вопроса набралось 4 ответа. Нужно вызывать ее только при создании

2018-10-09 10:44 UTC, iBublik commented on app/models/answer.rb
> +    errors.add(:question_id, "There is already maximum number of questions (#{MAX_NUM_ANSWERS})")
Лучше ошибку цеплять прямо к `:question`

2018-10-09 10:44 UTC, iBublik commented on app/models/category.rb
> +  scope :asc, -> { order(title: :asc) }
В задании речь шла именно про скоуп _по умолчанию_. Для этого есть отдельный метод

2018-10-09 10:44 UTC, iBublik commented on app/models/test.rb
>      joins(:category).where(categories: {title: category_title}).order(:title).pluck(:title)
Скоупы должны быть способны выстраиваться в цепочку вызовов - `Test.easy.created_last_week.where(...)`. Для этого скоуп должен вовзращать ActiveRecord::Relation (это как раз то что возвращают методы запросов `where`, `order` и т.д.). У тебя тут возвращается массив, так что после вызова этого скоупа другой уже не применить. Либо оставь метод класса, либо часть выдели в скоуп, а часть оставь в методе класса

2018-10-09 10:44 UTC, iBublik commented on db/migrate/20181007190358_add_unique_index_to_tests.rb
> +    add_index :tests, [:title, :level], unique: true
Обратный порядок полей в индексе будет лучше. Тогда скоупы, которые ищут тест по уровню, смогут его использовать.
Чтиво на досуг по этой теме - https://use-the-index-luke.com/sql/where-clause/the-equals-operator/concatenated-keys

2018-10-09 19:16 UTC, k-gavrilov commented on app/models/answer.rb
> +    errors.add(:question_id, "There is already maximum number of questions (#{MAX_NUM_ANSWERS})")
А тут вроде говорят имена атрибутов надо использовать: https://guides.rubyonrails.org/active_record_validations.html#working-with-validation-errors
Верю опытному разработчику, но если есть какая-нибудь ссылочка почитать, буду благодарен=)

2018-10-11 07:16 UTC, iBublik commented on app/models/answer.rb
> +    errors.add(:question_id, "There is already maximum number of questions (#{MAX_NUM_ANSWERS})")
Вопрос - это тоже атрибут модели, просто он виртуальный (т.е. не хранится физически в базе, а вычисляется на основе других атрибутов)

2018-10-11 07:21 UTC, iBublik approved these changes

2018-10-11 07:21 UTC, iBublik commented on app/models/category.rb
> +  default_scope { order(title: :asc) }
Скоуп по умолчанию меняет поведение всех запросов этой модели. Это важное изменение, которое надо держать на виду - в самом верху класса

2018-10-11 07:21 UTC, iBublik commented on app/models/test.rb
> +  scope :having_category, (lambda do |category_title|
Чисто стилистическое имхо:
- метод лучше назвать `by_category`
- скобки смотрятся жутковато, лучше использовать такой формат записи:
```ruby
-> (category) {
  ...
}
```

2018-10-14 06:17 UTC, merged